blank_issues_enabled: false
contact_links:
  - name: Scorncord Support Server
    url: https://discord.gg/574gU979yp
    about: If you need help regarding Scorncord, please join our support server!
  - name: Scorncord Installer
    url: https://github.com/Scorncord/Installer
    about: You can find the Scorncord Installer here
